{{- if and .Values.config.enabled  .Values.config.data -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.fullname" . }}
  labels:
    {{- include "config.labels" . | nindent 4 }}
    {{- with .Values.config.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.config.data }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
