{{- if and .Values.secret.enabled  .Values.secret.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.fullname" . }}
  labels:
    {{- include "config.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type }}
stringData:
  {{- with .Values.secret.data }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
