{{- if and .Values.server.enabled .Values.autoscaling.enabled (not .Values.worker.enabled) -}}
{{- $fullname := include "server.fullname" . -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.autoscaling.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullname }}
  minReplicas: {{ include "server.minReplicas" . }}
  maxReplicas: {{ include "server.maxReplicas" . }}
  metrics:
{{- with .Values.autoscaling.cpu }}
    - type: Resource
      resource:
        name: cpu
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.autoscaling.memory }}
    - type: Resource
      resource:
        name: memory
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
