{{- if  .Values.migration.enabled -}}
{{- $name := include "migration.name" . -}}
{{- $fullname := include "migration.fullname" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "migration.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "migration.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.migration.autoReload }}
    reloader.stakater.com/auto: "true"
    {{- end }}
  {{- with .Values.migration.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        name: {{ $name }}
        app-name: {{ .Values.meta.name }}
        version: {{ include "meta.version" . }}
        env: {{ .Values.meta.env }}
        chart-name: {{ .Chart.Name }}
        chart-version: {{ .Chart.Version }}
      annotations:
        sidecar.istio.io/inject: {{ .Values.migration.istio.injected | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: "{{ .Values.image.repository }}:{{ include "image.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.migration.command }}
          command:
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
          {{- if or .Values.secrets.envFrom .Values.configMaps.envFrom }}
          envFrom:
          {{- with .Values.secrets.envFrom }}
          {{- range . }}
            - secretRef:
                name: {{ tpl . $ }}
          {{- end }}
          {{- end }}
          {{- with .Values.configMaps.envFrom }}
          {{- range . }}
            - configMapRef:
                name: {{ tpl . $ }}
          {{- end }}
          {{- end }}
          {{- end }}
          env:
            - name: ENV_NAME
              value: {{ .Values.meta.env }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- with .Values.secrets.env }}
            {{- range $secret := . }}
            {{- range .keys }}
            - name: {{ tpl . $ }}
              valueFrom:
                secretKeyRef:
                  name: {{ tpl $secret.name $ }}
                  key: {{ tpl . $ }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- with .Values.configMaps.env }}
            {{- range $configMap := . }}
            {{- range .keys }}
            - name: {{ tpl . $ }}
              valueFrom:
                configMapKeyRef:
                  name: {{ tpl $configMap.name $ }}
                  key: {{ tpl . $ }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- with .Values.migration.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if or .Values.secrets.volumes .Values.configMaps.volumes .Values.extraVolumeMounts }}
          volumeMounts:
          {{- with .Values.secrets.volumes }}
          {{- range $secret := . }}
          {{- range .mounts }}
            - name: {{ tpl $secret.name $ }}-secret
              mountPath: {{ tpl .mountPath $ }}
              {{- with .subPath }}
              subPath: {{ . }}
              {{- end }}
              {{- with .readOnly }}
              readOnly: {{ . }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.configMaps.volumes }}
          {{- range $configMap := . }}
          {{- range .mounts }}
            - name: {{ tpl $configMap.name $ }}-config
              mountPath: {{ tpl .mountPath $ }}
              {{- with .subPath }}
              subPath: {{ . }}
              {{- end }}
              {{- with .readOnly }}
              readOnly: {{ . }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- include "tplValue" (dict "value" . "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- if or .Values.secrets.volumes .Values.configMaps.volumes .Values.extraVolumes  }}
      volumes:
      {{- with .Values.secrets.volumes }}
      {{- range . }}
        - name: {{ tpl .name $ }}-secret
          secret:
            secretName: {{ tpl .name $ }}
      {{- end }}
      {{- end }}
      {{- with .Values.configMaps.volumes }}
      {{- range . }}
        - name: {{ tpl .name $ }}-config
          configMap:
            name: {{ tpl .name $ }}
      {{- end }}
      {{- end }}
      {{- with .Values.extraVolumes }}
        {{- include "tplValue" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- end }}
      restartPolicy: {{ .Values.migration.restartPolicy }}
      dnsPolicy: {{ .Values.migration.dnsPolicy }}
      {{- with .Values.migration.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migration.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migration.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: {{ .Values.migration.backoffLimit }}
  {{- with .Values.migration.deadlineSeconds }}
  activeDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with .Values.migration.ttlSeconds }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
{{- end }}

